# Generated by Django 4.1.6 on 2023-02-20 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories', '0002_eattype'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalorieHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество в граммах')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_history', to='calories.products', verbose_name='Продукт')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_in_history', to='calories.eattype', verbose_name='Время приема пищи(завтрак, обед, ужин)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calorie_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
