# Generated by Django 4.1.6 on 2023-02-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0003_usercaloriehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название упражнения')),
                ('calories_count', models.IntegerField(verbose_name='Количество калорий')),
            ],
        ),
        migrations.AlterModelOptions(
            name='usercaloriehistory',
            options={'verbose_name': 'История добавления каллорий', 'verbose_name_plural': 'История добавления каллорий'},
        ),
        migrations.AlterField(
            model_name='products',
            name='calories',
            field=models.IntegerField(verbose_name='Калории'),
        ),
    ]
