# Generated by Django 4.1.6 on 2023-02-27 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories', '0004_sportsexercises_alter_usercaloriehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportsexercises',
            options={'verbose_name': 'Упражнение', 'verbose_name_plural': 'Упражнения'},
        ),
        migrations.CreateModel(
            name='UserRemoveCalorieHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(verbose_name='Количество часов за упражнением')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления упражнения')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_in_remove_history', to='calories.sportsexercises', verbose_name='Время приема пищи(завтрак, обед, ужин)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remove_calorie_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История добавления физ. нагрузки',
                'verbose_name_plural': 'История добавления физ. нагрузок',
            },
        ),
    ]
