# Generated by Django 4.1.6 on 2023-02-27 06:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories', '0005_alter_sportsexercises_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCalorieHistory',
            new_name='UserAddCalorieHistory',
        ),
    ]
