# Generated by Django 4.1.6 on 2023-02-27 07:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0006_rename_usercaloriehistory_useraddcaloriehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userremovecaloriehistory',
            name='custom_type',
            field=models.CharField(max_length=256, null=True, verbose_name='Кастомный тип физ. нагрузки'),
        ),
        migrations.AlterField(
            model_name='userremovecaloriehistory',
            name='hours',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество часов за упражнением'),
        ),
        migrations.AlterField(
            model_name='userremovecaloriehistory',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_in_remove_history', to='calories.sportsexercises', verbose_name='Тип физической нагрузки'),
        ),
    ]
