# Generated by Django 4.1.6 on 2023-02-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0007_userremovecaloriehistory_custom_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userremovecaloriehistory',
            name='hours',
            field=models.FloatField(verbose_name='Количество часов за упражнением'),
        ),
    ]
