# Generated by Django 4.1.6 on 2023-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0008_alter_userremovecaloriehistory_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='userremovecaloriehistory',
            name='calories',
            field=models.IntegerField(null=True, verbose_name='Количество калорий'),
        ),
    ]
