# Generated by Django 4.1.6 on 2023-02-28 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0009_userremovecaloriehistory_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userremovecaloriehistory',
            name='hours',
        ),
        migrations.AddField(
            model_name='userremovecaloriehistory',
            name='minutes',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Количество часов за упражнением'),
            preserve_default=False,
        ),
    ]
